server:
  port: 8762
eureka:
  server:
    enable-self-preservation: false
  instance:
#      appname: provider-service
      hostname: server2
  client:
      service-url:
        defaultZone:
          http://server1:8761/eureka/
      #register-with-eureka: false
      #fetch-registry: false
spring:
  application:
    name: provider-service