spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Sun9611/springcloudconfig
          username: 13347891121
          password: 961121Sjb
eureka:
  client:
    service-url:
      defaultZone:
        http://server1:8761/eureka/

server:
  port: 5000
